---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: vaultwarden
    app.kubernetes.io/instance: vaultwarden
  name: vw-secret
  namespace: vaultwarden
type: Opaque
stringData:
  WEBSOCKET_ENABLED: 'true'
  SENDS_ALLOWED: 'true'
  PASSWORD_ITERATIONS: '500000'
  SIGNUPS_ALLOWED: 'false'
  # SIGNUPS_VERIFY: 'true'
  # SIGNUPS_DOMAINS_WHITELIST: 'domain.tld'
  # INVITATIONS_ALLOWED: 'false'
  # ADMIN_TOKEN: 'some random string' #generate with openssl rand
  DOMAIN: 'https://vaultwarden.domain.tld'
  # SMTP_HOST: 'smtp server'
  # SMTP_FROM: 'sender email e.g: you@domain.tld'
  # SMTP_FROM_NAME: 'sender name'
  # SMTP_SECURITY: 'starttls'
  # SMTP_PORT: 587
  # SMTP_USERNAME: 'smtp username'
  # SMTP_PASSWORD: 'smtp password'
  # SMTP_TIMEOUT: 15
  PUSH_ENABLED: 'true'
  PUSH_INSTALLATION_ID: 'INSTALLATION_ID_PUSH'
  PUSH_INSTALLATION_KEY: 'INSTALLATION_KEY_PUSH'
  LOG_FILE: '/data/vaultwarden.log'
  LOG_LEVEL: 'debug'
  # LOG_LEVEL: 'warn'
  EXTENDED_LOGGING: 'true'
  TZ: 'TIMEZONE'
  YUBICO_CLIENT_ID: 'CLIENT_ID_YUBICO'
  YUBICO_SECRET_KEY: 'SECRET_KEY_YUBICO'
